-- What the game calls a quest category that is not a zone. GENERATED - see
-- tools/quest-sorts.py.
--
-- A quest log groups by heading, and a heading is a word. Most of them are zones and a
-- zone has an id, so those already read in the language of whoever is looking. The rest
-- had nothing: a warlock's quests sit under "Demoniste" on a French client and
-- "Warlock" on an English one, and so did the profession headings - which are not the
-- profession names either, the French for Cooking being "Cuisine" while the heading
-- says "Cuisinier".
--
-- Read by the **word**, not by an id: nothing records one of these, so what a reader has
-- is whatever the recording client wrote. Every build's names sit in one row for that
-- reason - a sort renamed between builds wants both words finding the same row.

local _, Family = ...

Family.QuestSorts = {
	[1] = {
		enUS = { "Epic" },
		deDE = { "Episch" },
		frFR = { "Épique" },
		esES = { "Épica" },
		ruRU = { "Эпические" },
	},
	[22] = {
		enUS = { "Seasonal" },
		deDE = { "Saisonbedingt" },
		frFR = { "Saisonnier" },
		esES = { "Estacional" },
		ruRU = { "Сезонные" },
	},
	[24] = {
		enUS = { "Herbalism" },
		deDE = { "Kräuterkunde" },
		frFR = { "Herboristerie" },
		esES = { "Botánica", "Herboristería" },
		ruRU = { "Травничество" },
	},
	[61] = {
		enUS = { "Warlock" },
		deDE = { "Hexenmeister" },
		frFR = { "Démoniste" },
		esES = { "Brujo" },
		ruRU = { "Чернокнижник", "Чернокнижница" },
	},
	[81] = {
		enUS = { "Warrior" },
		deDE = { "Krieger" },
		frFR = { "Guerrier" },
		esES = { "Guerrero" },
		ruRU = { "Воин" },
	},
	[82] = {
		enUS = { "Shaman" },
		deDE = { "Schamane" },
		frFR = { "Chaman" },
		esES = { "Chamán" },
		ruRU = { "Шаман", "Шаманка" },
	},
	[101] = {
		enUS = { "Fishing" },
		deDE = { "Angeln" },
		frFR = { "Pêcheur" },
		esES = { "Pesca" },
		ruRU = { "Рыбная ловля" },
	},
	[121] = {
		enUS = { "Blacksmithing" },
		deDE = { "Schmiedekunst" },
		frFR = { "Forgeron" },
		esES = { "Herrería" },
		ruRU = { "Кузнечное дело" },
	},
	[141] = {
		enUS = { "Paladin" },
		deDE = { "Paladin" },
		frFR = { "Paladin" },
		esES = { "Paladín" },
		ruRU = { "Паладин" },
	},
	[161] = {
		enUS = { "Mage" },
		deDE = { "Magier" },
		frFR = { "Mage" },
		esES = { "Mago" },
		ruRU = { "Маг" },
	},
	[162] = {
		enUS = { "Rogue" },
		deDE = { "Schurke" },
		frFR = { "Voleur" },
		esES = { "Pícaro" },
		ruRU = { "Разбойник", "Разбойница" },
	},
	[181] = {
		enUS = { "Alchemy" },
		deDE = { "Alchimie", "Alchemie" },
		frFR = { "Alchimiste" },
		esES = { "Alquimia" },
		ruRU = { "Алхимия" },
	},
	[182] = {
		enUS = { "Leatherworking" },
		deDE = { "Lederverarbeitung" },
		frFR = { "Artisan du cuir", "Travailleur du cuir" },
		esES = { "Peletería" },
		ruRU = { "Кожевничество" },
	},
	[201] = {
		enUS = { "Engineering" },
		deDE = { "Ingenieurskunst" },
		frFR = { "Ingénieur" },
		esES = { "Ingeniería" },
		ruRU = { "Инженерное дело" },
	},
	[221] = {
		enUS = { "Treasure Map" },
		deDE = { "Schatzkarte" },
		frFR = { "Carte au trésor" },
		esES = { "Mapa de tesoro" },
		ruRU = { "Поиск кладов" },
	},
	[261] = {
		enUS = { "Hunter" },
		deDE = { "Jäger" },
		frFR = { "Chasseur" },
		esES = { "Cazador" },
		ruRU = { "Охотник", "Охотница" },
	},
	[262] = {
		enUS = { "Priest" },
		deDE = { "Priester" },
		frFR = { "Prêtre" },
		esES = { "Sacerdote" },
		ruRU = { "Жрец", "Жрица" },
	},
	[263] = {
		enUS = { "Druid" },
		deDE = { "Druide" },
		frFR = { "Druide" },
		esES = { "Druida" },
		ruRU = { "Друид" },
	},
	[264] = {
		enUS = { "Tailoring" },
		deDE = { "Schneiderei" },
		frFR = { "Tailleur" },
		esES = { "Sastrería" },
		ruRU = { "Портняжное дело" },
	},
	[284] = {
		enUS = { "Special" },
		deDE = { "Spezial" },
		frFR = { "Spécial" },
		esES = { "Especial" },
		ruRU = { "Особые" },
	},
	[304] = {
		enUS = { "Cooking" },
		deDE = { "Kochkunst" },
		frFR = { "Cuisinier" },
		esES = { "Cocina" },
		ruRU = { "Кулинария" },
	},
	[324] = {
		enUS = { "First Aid" },
		deDE = { "Erste Hilfe" },
		frFR = { "Premiers soins", "Secourisme" },
		esES = { "Primeros auxilios" },
		ruRU = { "Первая помощь" },
	},
	[344] = {
		enUS = { "Legendary" },
		deDE = { "Legendär" },
		frFR = { "Légendaire" },
		esES = { "Legendaria" },
		ruRU = { "Легенды" },
	},
	[364] = {
		enUS = { "Darkmoon Faire" },
		deDE = { "Dunkelmond-Jahrmarkt" },
		frFR = { "Foire de Sombrelune" },
		esES = { "Feria de la Luna Negra" },
		ruRU = { "Ярмарка Новолуния" },
	},
	[365] = {
		enUS = { "Ahn'Qiraj War" },
		deDE = { "Krieg von Ahn'Qiraj" },
		frFR = { "Guerre d'Ahn'Qiraj" },
		esES = { "Guerra de Ahn'Qiraj" },
		ruRU = { "Ан'киражская война" },
	},
	[366] = {
		enUS = { "Lunar Festival" },
		deDE = { "Mondfest" },
		frFR = { "Fête lunaire" },
		esES = { "Festival Lunar" },
		ruRU = { "Лунный фестиваль" },
	},
	[367] = {
		enUS = { "Reputation" },
		deDE = { "Ruf" },
		frFR = { "Réputation" },
		esES = { "Reputación" },
		ruRU = { "Репутация" },
	},
	[368] = {
		enUS = { "Invasion" },
		deDE = { "Invasion der Geißel" },
		frFR = { "Invasion" },
		esES = { "Invasión" },
		ruRU = { "Вторжение" },
	},
	[369] = {
		enUS = { "Midsummer" },
		deDE = { "Sonnenwendfest" },
		frFR = { "Solstice d'été" },
		esES = { "Verano" },
		ruRU = { "Огненный солнцеворот" },
	},
	[370] = {
		enUS = { "Brewfest" },
		deDE = { "Braufest" },
		frFR = { "Fête des Brasseurs" },
		esES = { "Fiesta de la cerveza", "Fiesta de la Cerveza" },
		ruRU = { "Хмельной фестиваль" },
	},
	[371] = {
		enUS = { "Inscription" },
		deDE = { "Inschriftenkunde" },
		frFR = { "Calligraphie" },
		esES = { "Inscripción" },
		ruRU = { "Начертание" },
	},
	[372] = {
		enUS = { "Death Knight" },
		deDE = { "Todesritter" },
		frFR = { "Chevalier de la mort" },
		esES = { "Caballero de la Muerte" },
		ruRU = { "Рыцарь смерти" },
	},
	[373] = {
		enUS = { "Jewelcrafting" },
		deDE = { "Juwelierskunst" },
		frFR = { "Joaillerie" },
		esES = { "Joyería" },
		ruRU = { "Ювелирное дело" },
	},
	[374] = {
		enUS = { "Noblegarden" },
		deDE = { "Nobelgarten" },
		frFR = { "Jardin des nobles" },
		esES = { "Jardín Noble" },
		ruRU = { "Сад чудес" },
	},
	[375] = {
		enUS = { "Pilgrim's Bounty" },
		deDE = { "Pilgerfreuden" },
		frFR = { "Bienfaits du pèlerin" },
		esES = { "Generosidad del Peregrino" },
		ruRU = { "Пиршество странников" },
	},
	[376] = {
		enUS = { "Love is in the Air" },
		deDE = { "Liebe liegt in der Luft" },
		frFR = { "De l'amour dans l'air" },
		esES = { "Amor en el aire" },
		ruRU = { "Любовная лихорадка" },
	},
	[377] = {
		enUS = { "Archaeology" },
		deDE = { "Archäologie" },
		frFR = { "Archéologie" },
		esES = { "Arqueología" },
		ruRU = { "Археология" },
	},
	[378] = {
		enUS = { "Children's Week" },
		deDE = { "Kinderwoche" },
		frFR = { "Semaine des enfants" },
		esES = { "La Semana de los Niños" },
		ruRU = { "Детская неделя" },
	},
	[379] = {
		enUS = { "Firelands Invasion" },
		deDE = { "Einmarsch in die Feuerlande" },
		frFR = { "Invasion des terres de Feu" },
		esES = { "Invasión de las Tierras de Fuego" },
		ruRU = { "Вторжение на Огненные Просторы" },
	},
	[380] = {
		enUS = { "The Zandalari" },
		deDE = { "Die Zandalari" },
		frFR = { "Les Zandalari" },
		esES = { "Los Zandalari" },
		ruRU = { "Племя Зандалар" },
	},
	[381] = {
		enUS = { "Elemental Bonds" },
		deDE = { "Elementare Bande" },
		frFR = { "Liens élémentaires" },
		esES = { "Vínculos elementales" },
		ruRU = { "Власть стихий" },
	},
	[391] = {
		enUS = { "Pandaren Brewmasters" },
		deDE = { "Pandarische Braumeister" },
		frFR = { "Maîtres brasseurs pandarens" },
		esES = { "Maestros cerveceros pandaren" },
		ruRU = { "Пандарены-пивовары" },
	},
	[392] = {
		enUS = { "Scenario" },
		deDE = { "Szenario" },
		frFR = { "Scénario" },
		esES = { "Gesta" },
		ruRU = { "Сценарий" },
	},
	[394] = {
		enUS = { "Battle Pets" },
		deDE = { "Kampfhaustiere" },
		frFR = { "Mascottes de combat" },
		esES = { "Mascotas de duelo" },
		ruRU = { "Боевые питомцы" },
	},
	[395] = {
		enUS = { "Monk" },
		deDE = { "Mönch" },
		frFR = { "Moine" },
		esES = { "Monje" },
		ruRU = { "Монах" },
	},
	[396] = {
		enUS = { "Landfall" },
		deDE = { "Landung" },
		frFR = { "Accostage" },
		esES = { "Desembarco" },
		ruRU = { "Высадка" },
	},
	[397] = {
		enUS = { "Pandaren Campaign" },
		deDE = { "Pandarenkampagne" },
		frFR = { "Campagne pandarène" },
		esES = { "Campaña pandaren" },
		ruRU = { "Пандаренская кампания" },
	},
	[398] = {
		enUS = { "Riding" },
		deDE = { "Reiten" },
		frFR = { "Monte" },
		esES = { "Equitación" },
		ruRU = { "Верховая езда" },
	},
	[399] = {
		enUS = { "Brawler's Guild" },
		deDE = { "Kampfgilde" },
		frFR = { "Les Bastonneurs" },
		esES = { "Hermandad de camorristas" },
		ruRU = { "Бойцовская гильдия" },
	},
	[400] = {
		enUS = { "Proving Grounds" },
		deDE = { "Die Feuerprobe" },
		frFR = { "Ordalie" },
		esES = { "Terreno de Pruebas" },
		ruRU = { "Арена испытаний" },
	},
	[641] = {
		enUS = { "Nightmare Incursions" },
		deDE = { "Alptraumeinfälle" },
		frFR = { "Incursions de cauchemar" },
		esES = { "Incursiones de la Pesadilla" },
		ruRU = { "Кошмарные вторжения" },
	},
	[644] = {
		enUS = { "Blackrock Eruption" },
		deDE = { "Ausbruch des Schwarzfels" },
		frFR = { "Éruption de Blackrock" },
		esES = { "Erupción de Roca Negra" },
		ruRU = { "Извержение Черной горы" },
	},
}
