-- Generated by tools/world-buffs.py. Do not edit.
--
-- The icon a world buff draws, back to the spell that draws it. A Chronoboon's
-- contents are tooltip text and the only identifier in a row is the icon's fileID
-- (DATASOURCES.md section 2), so this is what turns a recorded fileID into a name -
-- by asking the client for the spell, in whatever language it is running in.
--
-- Nothing that *records* reads this table. A world buff Blizzard adds tomorrow is
-- recorded correctly by a client that has never seen a regenerated copy of it; it
-- would simply be drawn as its own icon with no name under it until this is re-run.

local _, Family = ...

Family.WorldBuffs = {
	[136109] = 22817, -- Fengus' Ferocity, all three builds
	[136054] = 22818, -- Mol'dar's Moxie, all three builds
	[135930] = 22820, -- Slip'kik's Savvy, all three builds
	[134153] = 22888, -- Rallying Cry of the Dragonslayer, all three builds
	[135759] = 16609, -- Warchief's Blessing, all three builds
	[132107] = 24425, -- Spirit of Zandalar, all three builds
	[135934] = 15366, -- Songflower Serenade, all three builds
	[134334] = 23768, -- Sayge's Dark Fortune of Damage, all three builds
	[236403] = 430947, -- Boon of Blackfathom, Classic Era
	[236424] = 438536, -- Spark of Inspiration, Classic Era
	[236368] = 446695, -- Fervor of the Temple Explorer, Classic Era
	[135763] = 460939, -- Might of Stormwind, Classic Era
}
