#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""What this project has cost, from the tool's own records and from what a person declares.

Two sources, kept apart on purpose.

**Derived** comes from Claude Code's transcripts, which timestamp every message and record the
token usage of every reply. It is exact about what happened inside the tool and blind to
everything outside it.

**Declared** comes from docs/effort/declared.csv, written by hand, and covers what the
transcripts cannot see: testing in the game, reading, thinking away from the keyboard. On an
addon that is not a small share.

They are never added into one headline figure without saying which is which. A number that is
half measured and half remembered, presented as one, is the kind of thing this repository
spends its time refusing elsewhere.

    tools/effort.py            print the report
    tools/effort.py --write    write docs/EFFORT.md as well
"""

import csv, datetime, glob, io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
LEDGER = os.path.join(ROOT, "docs", "effort", "declared.csv")
REPORT = os.path.join(ROOT, "docs", "EFFORT.md")

# Claude Code files a directory per working directory. This project has had two - the tree was
# rebuilt as Family-public - and both are its history.
TRANSCRIPTS = [
    os.path.expanduser("~/.claude/projects/-home-dietpi-dev-Family"),
    os.path.expanduser("~/.claude/projects/-home-dietpi-dev-Family-public"),
]

# A gap longer than this is somebody having stopped. Three of them are reported rather than
# one, because the answer for human time is extremely sensitive to the choice and the answer
# for machine time is not - and that difference is the finding, not a detail of it.
THRESHOLDS = (120, 300, 600)


def parse(stamp):
    return datetime.datetime.fromisoformat(stamp.replace("Z", "+00:00"))


def hm(seconds):
    seconds = int(seconds)
    return "%dh %02dm" % (seconds // 3600, (seconds % 3600) // 60)


def events():
    """Every timestamped message, with who produced it, oldest first."""
    out, sessions = [], {}
    for folder in TRANSCRIPTS:
        for path in glob.glob(os.path.join(folder, "*.jsonl")):
            with open(path, encoding="utf-8", errors="replace") as handle:
                for line in handle:
                    try:
                        record = json.loads(line)
                    except ValueError:
                        continue

                    stamp, kind = record.get("timestamp"), record.get("type")
                    if not stamp or kind not in ("user", "assistant"):
                        continue

                    when = parse(stamp)
                    human = kind == "user" and (record.get("origin") or {}).get(
                        "kind") == "human"
                    who = "you" if human else ("claude" if kind == "assistant" else "tool")

                    usage = (record.get("message") or {}).get("usage") or {}
                    out.append((when, who, usage))

                    key = os.path.basename(path)[:8]
                    seen = sessions.setdefault(key, {"first": when, "last": when, "you": 0})
                    seen["first"] = min(seen["first"], when)
                    seen["last"] = max(seen["last"], when)
                    if human:
                        seen["you"] += 1
    out.sort(key=lambda row: row[0])
    return out, sessions


def declared():
    """What a person wrote down, or nothing if they have not written anything yet."""
    rows = []
    if not os.path.exists(LEDGER):
        return rows
    with open(LEDGER, encoding="utf-8") as handle:
        text = "\n".join(l for l in handle.read().splitlines()
                         if l.strip() and not l.lstrip().startswith("#"))
    for row in csv.reader(io.StringIO(text)):
        if len(row) < 4:
            continue
        try:
            hours = float(row[1])
        except ValueError:
            continue
        rows.append({"date": row[0].strip(), "hours": hours,
                     "who": row[2].strip(), "what": row[3].strip()})
    return rows


def report():
    log, sessions = events()
    lines = []
    add = lines.append

    if not log:
        return "No transcripts found. Check the paths at the top of tools/effort.py.\n"

    add("# Family — what it cost")
    add("")
    add("GENERATED by `tools/effort.py`. Do not edit: the declared half lives in")
    add("`docs/effort/declared.csv` and is the only part written by hand.")
    add("")
    add("Two sources, kept apart. **Derived** is exact about what happened inside Claude Code")
    add("and blind to everything outside it. **Declared** is what a person remembers of the")
    add("rest. They are not added together into one figure, because half of that figure would")
    add("be a measurement and half a recollection.")
    add("")

    add("## Derived, from the transcripts")
    add("")
    add("Every gap between consecutive messages is attributed to whoever produced the message")
    add("that *ended* it: a gap closing on a reply is generation, one closing on a tool result")
    add("is a command running, one closing on your message is you reading and typing.")
    add("")
    add("| idle threshold | you | Claude generating | tools running | total |")
    add("|---|---|---|---|---|")
    for idle in THRESHOLDS:
        bucket = {"you": 0.0, "claude": 0.0, "tool": 0.0}
        for (before, _, _), (after, who, _) in zip(log, log[1:]):
            gap = (after - before).total_seconds()
            if gap <= idle:
                bucket[who] += gap
        add("| %d min | %s | %s | %s | %s |"
            % (idle // 60, hm(bucket["you"]), hm(bucket["claude"]),
               hm(bucket["tool"]), hm(sum(bucket.values()))))
    add("")
    add("**Claude's own time is the trustworthy row and yours is not.** Generation barely")
    add("moves with the threshold, because a reply's parts follow each other in seconds.")
    add("Yours swings several-fold, because your gaps are genuinely everything from a one-word")
    add("answer to twenty minutes in a bank. For human time the threshold is not a parameter,")
    add("it is the answer — which is why the declared ledger below exists at all.")
    add("")

    tokens = {"input_tokens": 0, "output_tokens": 0,
              "cache_creation_input_tokens": 0, "cache_read_input_tokens": 0}
    for _, _, usage in log:
        for field in tokens:
            tokens[field] += usage.get(field) or 0

    add("| tokens | |")
    add("|---|---|")
    add("| fresh input | %s |" % "{:,}".format(tokens["input_tokens"]))
    add("| cache writes | %s |" % "{:,}".format(tokens["cache_creation_input_tokens"]))
    add("| cache reads | %s |" % "{:,}".format(tokens["cache_read_input_tokens"]))
    add("| output | %s |" % "{:,}".format(tokens["output_tokens"]))
    add("")
    add("Cache reads dominate and mean less than they look: every request re-sends the whole")
    add("conversation, so the same context is read back thousands of times and is priced for")
    add("that. The work done is the output and the cache writes.")
    add("")

    first = min(s["first"] for s in sessions.values())
    last = max(s["last"] for s in sessions.values())
    add("%d sessions, %s to %s, %d prompts from you."
        % (len(sessions), first.strftime("%d %b %Y"), last.strftime("%d %b %Y"),
           sum(s["you"] for s in sessions.values())))
    add("")

    add("## Declared, by hand")
    add("")
    rows = declared()
    if not rows:
        add("Nothing declared yet. `docs/effort/declared.csv` takes a row per stretch of work")
        add("the transcripts cannot see — testing in the game above all.")
    else:
        add("| date | hours | who | what |")
        add("|---|---|---|---|")
        for row in sorted(rows, key=lambda r: r["date"]):
            add("| %s | %.1f | %s | %s |"
                % (row["date"], row["hours"], row["who"], row["what"]))
        add("")
        add("**%.1f hours declared**, across %d entries."
            % (sum(r["hours"] for r in rows), len(rows)))
    add("")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = report()
    sys.stdout.write(text)
    if "--write" in sys.argv:
        open(REPORT, "w", encoding="utf-8").write(text)
        print("\n-> docs/EFFORT.md", file=sys.stderr)
