#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Lists what Family asks of the client, and writes it where tools/FamilySurface reads it.

Midnight is the first client Family was not written against, and the first question about it
is not what Retail has but what Family *touches*. That is countable, so it is counted rather
than recalled: every global a Family file reads, taken from the compiler's own bytecode
listing (`luac5.1 -l`), which sees exactly the names the code looks up and nothing a comment
mentions.

The listing cannot see three things, so each is gathered its own way:

- **Members of the client's namespaces** - `C_Item.GetItemInfo` is one global read and a
  field. Taken from the bytecode where the field is read off the register the global landed
  in, and from the source for the files that copy a namespace into a local first.
- **Events** - a string handed to `RegisterEvent`, often out of a table. Every upper-case
  string literal is kept and the probe asks the client about each, so the list is generous
  on purpose: a literal that is not an event is refused on every client, and only a refusal
  a Classic client does not also give means anything.
- **Frame templates** - a string handed to `CreateFrame`, kept with the frame type it was
  handed with, because a template built on the wrong type can throw on every client.

    tools/surface.py             write tools/FamilySurface/Surface.lua
    tools/surface.py --check     exit 1 if that file is not what this would write

Re-run after every `git merge main`: a merge that brings in a new call brings in a new
question for the client.
"""

import glob, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "FamilySurface", "Surface.lua")

# Lua's own library and the handful of Lua-level helpers every client defines in its own
# FrameXML. They are not questions about the game.
LUA = set("""
_G assert error ipairs pairs next pcall xpcall select tonumber tostring type unpack rawget
rawset rawequal setmetatable getmetatable math string table coroutine print loadstring
""".split())


def sources():
    files = glob.glob(os.path.join(ROOT, "addons", "Family*", "**", "*.lua"), recursive=True)
    return sorted(f for f in files if os.sep + "Libs" + os.sep not in f)


def listing(path):
    run = subprocess.run(["luac5.1", "-p", "-l", path], capture_output=True, text=True)
    if run.returncode != 0:
        sys.exit("luac5.1 refused %s:\n%s" % (path, run.stderr))
    return run.stdout.splitlines()


GLOBAL = re.compile(r"\t(GETGLOBAL|SETGLOBAL)\s+(\d+)\s+-?\d+\s*; (\S+)$")
FIELD = re.compile(r"\t(?:GETTABLE|SELF)\s+-?\d+\s+(\d+)\s+-?\d+\s*; \"(\w+)\"$")
NAMESPACE = re.compile(r"^(C_\w+|Enum|TooltipDataProcessor)$")


def uncommented(text):
    text = re.sub(r"--\[(=*)\[.*?\]\1\]", "", text, flags=re.S)
    return re.sub(r"--[^\n]*", "", text)


def measure():
    reads, writes, members, strings, templates = set(), set(), set(), set(), set()
    for path in sources():
        lines = listing(path)
        for index, line in enumerate(lines):
            found = GLOBAL.search(line)
            if not found:
                continue
            op, register, name = found.groups()
            (reads if op == "GETGLOBAL" else writes).add(name)
            if op == "GETGLOBAL" and NAMESPACE.match(name) and index + 1 < len(lines):
                field = FIELD.search(lines[index + 1])
                if field and field.group(1) == register:
                    members.add(name + "." + field.group(2))

        text = uncommented(open(path, encoding="utf-8").read())
        for space, field in re.findall(r"\b(C_\w+|Enum|TooltipDataProcessor)\.(\w+)", text):
            members.add(space + "." + field)
        strings.update(re.findall(r"[\"']([A-Z][A-Z0-9_]{3,})[\"']", text))
        for kind, template in re.findall(
                r"CreateFrame\(\s*[\"'](\w+)[\"'][^)]*?[\"'](\w*Template\w*)[\"']", text):
            templates.add(kind + ":" + template)

    globals_ = sorted(reads - writes - LUA)
    return globals_, sorted(members), sorted(strings), sorted(templates)


def lua_list(name, values):
    body = "".join('\t"%s",\n' % value for value in values)
    return "Surface.%s = {\n%s}\n" % (name, body)


def render():
    globals_, members, strings, templates = measure()
    return (
        "-- Generated by tools/surface.py from the Family sources. Do not edit: re-run it.\n"
        "--\n"
        "-- %d globals, %d namespace members, %d upper-case literals, %d frame templates.\n"
        "\n"
        "local _, Surface = ...\n"
        "\n" % (len(globals_), len(members), len(strings), len(templates))
        + lua_list("globals", globals_) + "\n"
        + lua_list("members", members) + "\n"
        + lua_list("literals", strings) + "\n"
        + lua_list("templates", templates)
    )


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            sys.exit("%s is out of date: run tools/surface.py" % os.path.relpath(OUT, ROOT))
        print("%s is current" % os.path.relpath(OUT, ROOT))
        return
    with open(OUT, "w", encoding="utf-8") as out:
        out.write(text)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print(text.splitlines()[2])


if __name__ == "__main__":
    main()
